// Copyright (C) 2026 Carlos Eduardo Rodrigues
// SPDX-License-Identifier: GPL-3.0-or-later

pub const NOMINAL_SIZES: &[u32] = &[24, 28, 32, 36, 40, 48, 64];

pub struct CursorDef {
    pub name: &'static str,
    pub hx: f32, // Normalized hotspot X (0.0 .. 1.0)
    pub hy: f32, // Normalized hotspot Y (0.0 .. 1.0)
    pub overrides: &'static [&'static str],
    pub animated_frames: Option<u32>, // None for static, Some(24) for progress/wait
    pub frame_delay_ms: u32,
}

pub const CURSOR_DEFS: &[CursorDef] = &[
    CursorDef {
        name: "alias",
        hx: 0.16,
        hy: 0.13,
        overrides: &["link"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "all-scroll",
        hx: 0.50,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "bottom_left_corner",
        hx: 0.16,
        hy: 0.84,
        overrides: &["ll_angle", "sw-resize"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "bottom_right_corner",
        hx: 0.84,
        hy: 0.84,
        overrides: &["lr_angle", "se-resize"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "bottom_side",
        hx: 0.50,
        hy: 0.84,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "cell",
        hx: 0.50,
        hy: 0.50,
        overrides: &["plus"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "center_ptr",
        hx: 0.47,
        hy: 0.19,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "col-resize",
        hx: 0.50,
        hy: 0.50,
        overrides: &["split_h"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "color-picker",
        hx: 0.08,
        hy: 0.91,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "context-menu",
        hx: 0.17,
        hy: 0.17,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "copy",
        hx: 0.16,
        hy: 0.13,
        overrides: &["dnd-copy"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "crosshair",
        hx: 0.48,
        hy: 0.48,
        overrides: &["cross"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "default",
        hx: 0.16,
        hy: 0.13,
        overrides: &["arrow", "left_ptr"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "dnd-move",
        hx: 0.50,
        hy: 0.50,
        overrides: &["closedhand", "dnd-none", "grabbing", "move"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "dnd-no-drop",
        hx: 0.50,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "down-arrow",
        hx: 0.50,
        hy: 0.84,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "draft",
        hx: 0.08,
        hy: 0.88,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "fleur",
        hx: 0.50,
        hy: 0.50,
        overrides: &["size_all"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "help",
        hx: 0.16,
        hy: 0.13,
        overrides: &["left_ptr_help", "question_arrow", "whats_this"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "left-arrow",
        hx: 0.13,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "left_side",
        hx: 0.13,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "no-drop",
        hx: 0.16,
        hy: 0.13,
        overrides: &["forbidden"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "not-allowed",
        hx: 0.50,
        hy: 0.50,
        overrides: &["circle", "crossed_circle"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "openhand",
        hx: 0.50,
        hy: 0.50,
        overrides: &["grab"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "pencil",
        hx: 0.08,
        hy: 0.91,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "pirate",
        hx: 0.50,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "pointer",
        hx: 0.39,
        hy: 0.19,
        overrides: &["hand1", "hand2", "pointing_hand"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "progress",
        hx: 0.16,
        hy: 0.13,
        overrides: &["half-busy", "left_ptr_watch"],
        animated_frames: Some(24),
        frame_delay_ms: 30,
    },
    CursorDef {
        name: "right-arrow",
        hx: 0.84,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "right_ptr",
        hx: 0.84,
        hy: 0.13,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "right_side",
        hx: 0.84,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "row-resize",
        hx: 0.50,
        hy: 0.50,
        overrides: &["split_v"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "size_bdiag",
        hx: 0.50,
        hy: 0.50,
        overrides: &["nesw-resize"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "size_fdiag",
        hx: 0.50,
        hy: 0.50,
        overrides: &["nwse-resize"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "size_hor",
        hx: 0.50,
        hy: 0.50,
        overrides: &["e-resize", "h_double_arrow", "sb_h_double_arrow", "w-resize"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "size_ver",
        hx: 0.50,
        hy: 0.50,
        overrides: &["n-resize", "s-resize", "sb_v_double_arrow", "v_double_arrow"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "text",
        hx: 0.47,
        hy: 0.47,
        overrides: &["ibeam", "xterm"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "top_left_corner",
        hx: 0.16,
        hy: 0.13,
        overrides: &["nw-resize", "ul_angle"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "top_right_corner",
        hx: 0.84,
        hy: 0.13,
        overrides: &["ne-resize", "ur_angle"],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "top_side",
        hx: 0.50,
        hy: 0.13,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "up-arrow",
        hx: 0.50,
        hy: 0.13,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "vertical-text",
        hx: 0.47,
        hy: 0.47,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "wait",
        hx: 0.50,
        hy: 0.50,
        overrides: &["watch"],
        animated_frames: Some(24),
        frame_delay_ms: 30,
    },
    CursorDef {
        name: "wayland-cursor",
        hx: 0.50,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "x-cursor",
        hx: 0.50,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "zoom-in",
        hx: 0.50,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
    CursorDef {
        name: "zoom-out",
        hx: 0.50,
        hy: 0.50,
        overrides: &[],
        animated_frames: None,
        frame_delay_ms: 0,
    },
];

pub const XCURSOR_ALIASES: &[(&str, &str)] = &[
    ("00000000000000020006000e7e9ffc3f", "progress"),
    ("00008160000006810000408080010102", "size_ver"),
    ("03b6e0fcb3499374a867c041f52298f0", "not-allowed"),
    ("08e8e1c95fe2fc01f976f1e063a24ccd", "progress"),
    ("1081e37283d90000800003c07f3ef6bf", "copy"),
    ("3085a0e285430894940527032f8b26df", "alias"),
    ("3ecb610c1bf2410f44200f48c40d3599", "progress"),
    ("4498f0e0c1937ffe01fd06f973665830", "dnd-move"),
    ("5c6cd98b3f3ebcb1f9c7f1c204630408", "help"),
    ("6407b0e94181790501fd1e167b474872", "copy"),
    ("640fb0e74195791501fd1ed57b41487f", "alias"),
    ("9081237383d90e509aa00f00170e968f", "dnd-move"),
    ("9d800788f1b08800ae810202380a0822", "pointer"),
    ("a2a266d0498c3104214a47bd64ab0fc8", "alias"),
    ("arrow", "default"),
    ("b66166c04f8c3109214a4fbd64a50fc8", "copy"),
    ("circle", "not-allowed"),
    ("closedhand", "dnd-move"),
    ("cross", "crosshair"),
    ("crossed_circle", "not-allowed"),
    ("d9ce0ab605698f320427677b458ad60b", "help"),
    ("dnd-copy", "copy"),
    ("dnd-none", "dnd-move"),
    ("e-resize", "size_hor"),
    ("e29285e634086352946a0e7090d73106", "pointer"),
    ("fcf21c00b30f7e3f83fe0dfd12e71cff", "dnd-move"),
    ("forbidden", "no-drop"),
    ("grab", "openhand"),
    ("grabbing", "dnd-move"),
    ("h_double_arrow", "size_hor"),
    ("half-busy", "progress"),
    ("hand1", "pointer"),
    ("hand2", "pointer"),
    ("ibeam", "text"),
    ("left_ptr", "default"),
    ("left_ptr_help", "help"),
    ("left_ptr_watch", "progress"),
    ("link", "alias"),
    ("ll_angle", "bottom_left_corner"),
    ("lr_angle", "bottom_right_corner"),
    ("move", "dnd-move"),
    ("n-resize", "size_ver"),
    ("ne-resize", "top_right_corner"),
    ("nesw-resize", "size_bdiag"),
    ("nw-resize", "top_left_corner"),
    ("nwse-resize", "size_fdiag"),
    ("plus", "cell"),
    ("pointing_hand", "pointer"),
    ("question_arrow", "help"),
    ("s-resize", "size_ver"),
    ("sb_h_double_arrow", "size_hor"),
    ("sb_v_double_arrow", "size_ver"),
    ("se-resize", "bottom_right_corner"),
    ("size_all", "fleur"),
    ("split_h", "col-resize"),
    ("split_v", "row-resize"),
    ("sw-resize", "bottom_left_corner"),
    ("ul_angle", "top_left_corner"),
    ("ur_angle", "top_right_corner"),
    ("v_double_arrow", "size_ver"),
    ("w-resize", "size_hor"),
    ("watch", "wait"),
    ("whats_this", "help"),
    ("xterm", "text"),
];
